/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditDuplicatesRouteImport } from './routes/audit-duplicates'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ApiCurateRouteImport } from './routes/api/curate'
import { Route as ApiDeleteImageRouteImport } from './routes/api/delete-image'
import { Route as ApiDeleteShootRouteImport } from './routes/api/delete-shoot'
import { Route as ApiNotifyLeadRouteImport } from './routes/api/notify-lead'
import { Route as ApiPublicShootRouteImport } from './routes/api/public-shoot'
import { Route as ApiSetShootPasswordRouteImport } from './routes/api/set-shoot-password'
import { Route as ApiShootRouteImport } from './routes/api/shoot'
import { Route as GalleryIdRouteImport } from './routes/gallery/$id'
import { Route as PublicGalleryIdRouteImport } from './routes/public-gallery/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditDuplicatesRoute = AuditDuplicatesRouteImport.update({
  id: '/audit-duplicates',
  path: '/audit-duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurateRoute = ApiCurateRouteImport.update({
  id: '/api/curate',
  path: '/api/curate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteImageRoute = ApiDeleteImageRouteImport.update({
  id: '/api/delete-image',
  path: '/api/delete-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteShootRoute = ApiDeleteShootRouteImport.update({
  id: '/api/delete-shoot',
  path: '/api/delete-shoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyLeadRoute = ApiNotifyLeadRouteImport.update({
  id: '/api/notify-lead',
  path: '/api/notify-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShootRoute = ApiPublicShootRouteImport.update({
  id: '/api/public-shoot',
  path: '/api/public-shoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetShootPasswordRoute = ApiSetShootPasswordRouteImport.update({
  id: '/api/set-shoot-password',
  path: '/api/set-shoot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShootRoute = ApiShootRouteImport.update({
  id: '/api/shoot',
  path: '/api/shoot',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/gallery/$id',
  path: '/gallery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicGalleryIdRoute = PublicGalleryIdRouteImport.update({
  id: '/public-gallery/$id',
  path: '/public-gallery/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-duplicates': typeof AuditDuplicatesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/delete-image': typeof ApiDeleteImageRoute
  '/api/delete-shoot': typeof ApiDeleteShootRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/api/public-shoot': typeof ApiPublicShootRoute
  '/api/set-shoot-password': typeof ApiSetShootPasswordRoute
  '/api/shoot': typeof ApiShootRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/public-gallery/$id': typeof PublicGalleryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-duplicates': typeof AuditDuplicatesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/delete-image': typeof ApiDeleteImageRoute
  '/api/delete-shoot': typeof ApiDeleteShootRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/api/public-shoot': typeof ApiPublicShootRoute
  '/api/set-shoot-password': typeof ApiSetShootPasswordRoute
  '/api/shoot': typeof ApiShootRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/public-gallery/$id': typeof PublicGalleryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-duplicates': typeof AuditDuplicatesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/delete-image': typeof ApiDeleteImageRoute
  '/api/delete-shoot': typeof ApiDeleteShootRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/api/public-shoot': typeof ApiPublicShootRoute
  '/api/set-shoot-password': typeof ApiSetShootPasswordRoute
  '/api/shoot': typeof ApiShootRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/public-gallery/$id': typeof PublicGalleryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-duplicates'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/upload'
    | '/api/curate'
    | '/api/delete-image'
    | '/api/delete-shoot'
    | '/api/notify-lead'
    | '/api/public-shoot'
    | '/api/set-shoot-password'
    | '/api/shoot'
    | '/gallery/$id'
    | '/public-gallery/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-duplicates'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/upload'
    | '/api/curate'
    | '/api/delete-image'
    | '/api/delete-shoot'
    | '/api/notify-lead'
    | '/api/public-shoot'
    | '/api/set-shoot-password'
    | '/api/shoot'
    | '/gallery/$id'
    | '/public-gallery/$id'
  id:
    | '__root__'
    | '/'
    | '/audit-duplicates'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/upload'
    | '/api/curate'
    | '/api/delete-image'
    | '/api/delete-shoot'
    | '/api/notify-lead'
    | '/api/public-shoot'
    | '/api/set-shoot-password'
    | '/api/shoot'
    | '/gallery/$id'
    | '/public-gallery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditDuplicatesRoute: typeof AuditDuplicatesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  UploadRoute: typeof UploadRoute
  ApiCurateRoute: typeof ApiCurateRoute
  ApiDeleteImageRoute: typeof ApiDeleteImageRoute
  ApiDeleteShootRoute: typeof ApiDeleteShootRoute
  ApiNotifyLeadRoute: typeof ApiNotifyLeadRoute
  ApiPublicShootRoute: typeof ApiPublicShootRoute
  ApiSetShootPasswordRoute: typeof ApiSetShootPasswordRoute
  ApiShootRoute: typeof ApiShootRoute
  GalleryIdRoute: typeof GalleryIdRoute
  PublicGalleryIdRoute: typeof PublicGalleryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-duplicates': {
      id: '/audit-duplicates'
      path: '/audit-duplicates'
      fullPath: '/audit-duplicates'
      preLoaderRoute: typeof AuditDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curate': {
      id: '/api/curate'
      path: '/api/curate'
      fullPath: '/api/curate'
      preLoaderRoute: typeof ApiCurateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-image': {
      id: '/api/delete-image'
      path: '/api/delete-image'
      fullPath: '/api/delete-image'
      preLoaderRoute: typeof ApiDeleteImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-shoot': {
      id: '/api/delete-shoot'
      path: '/api/delete-shoot'
      fullPath: '/api/delete-shoot'
      preLoaderRoute: typeof ApiDeleteShootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-lead': {
      id: '/api/notify-lead'
      path: '/api/notify-lead'
      fullPath: '/api/notify-lead'
      preLoaderRoute: typeof ApiNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-shoot': {
      id: '/api/public-shoot'
      path: '/api/public-shoot'
      fullPath: '/api/public-shoot'
      preLoaderRoute: typeof ApiPublicShootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/set-shoot-password': {
      id: '/api/set-shoot-password'
      path: '/api/set-shoot-password'
      fullPath: '/api/set-shoot-password'
      preLoaderRoute: typeof ApiSetShootPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shoot': {
      id: '/api/shoot'
      path: '/api/shoot'
      fullPath: '/api/shoot'
      preLoaderRoute: typeof ApiShootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/gallery/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-gallery/$id': {
      id: '/public-gallery/$id'
      path: '/public-gallery/$id'
      fullPath: '/public-gallery/$id'
      preLoaderRoute: typeof PublicGalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditDuplicatesRoute: AuditDuplicatesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  UploadRoute: UploadRoute,
  ApiCurateRoute: ApiCurateRoute,
  ApiDeleteImageRoute: ApiDeleteImageRoute,
  ApiDeleteShootRoute: ApiDeleteShootRoute,
  ApiNotifyLeadRoute: ApiNotifyLeadRoute,
  ApiPublicShootRoute: ApiPublicShootRoute,
  ApiSetShootPasswordRoute: ApiSetShootPasswordRoute,
  ApiShootRoute: ApiShootRoute,
  GalleryIdRoute: GalleryIdRoute,
  PublicGalleryIdRoute: PublicGalleryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
