/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ApiCurateRouteImport } from './routes/api/curate'
import { Route as ApiNotifyLeadRouteImport } from './routes/api/notify-lead'
import { Route as GalleryIdRouteImport } from './routes/gallery/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurateRoute = ApiCurateRouteImport.update({
  id: '/api/curate',
  path: '/api/curate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyLeadRoute = ApiNotifyLeadRouteImport.update({
  id: '/api/notify-lead',
  path: '/api/notify-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/gallery/$id',
  path: '/gallery/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/upload': typeof UploadRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/gallery/$id': typeof GalleryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/upload': typeof UploadRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/gallery/$id': typeof GalleryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/upload': typeof UploadRoute
  '/api/curate': typeof ApiCurateRoute
  '/api/notify-lead': typeof ApiNotifyLeadRoute
  '/gallery/$id': typeof GalleryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/upload'
    | '/api/curate'
    | '/api/notify-lead'
    | '/gallery/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/upload'
    | '/api/curate'
    | '/api/notify-lead'
    | '/gallery/$id'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/upload'
    | '/api/curate'
    | '/api/notify-lead'
    | '/gallery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  UploadRoute: typeof UploadRoute
  ApiCurateRoute: typeof ApiCurateRoute
  ApiNotifyLeadRoute: typeof ApiNotifyLeadRoute
  GalleryIdRoute: typeof GalleryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curate': {
      id: '/api/curate'
      path: '/api/curate'
      fullPath: '/api/curate'
      preLoaderRoute: typeof ApiCurateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-lead': {
      id: '/api/notify-lead'
      path: '/api/notify-lead'
      fullPath: '/api/notify-lead'
      preLoaderRoute: typeof ApiNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/gallery/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  UploadRoute: UploadRoute,
  ApiCurateRoute: ApiCurateRoute,
  ApiNotifyLeadRoute: ApiNotifyLeadRoute,
  GalleryIdRoute: GalleryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
